repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-yaml
      - id: detect-private-key
      - id: name-tests-test
        args: [--django]

  # - repo: https://github.com/psf/black
  #   rev: 22.10.0
  #   hooks:
  #     - id: black
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.9"
    hooks:
      - id: bandit

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
