version: '3.8'

services:
  inviscopilot:
    build: .
    ports:
      - "3978:3978"
    env_file:
      - ./src/.env
    volumes:
      - .:/app
    command: ["python", "src/app.py"]
    #command: ["tail", "-f", "/dev/null"]
