name: '02 - Create Docker Image'

on:
  push:
    branches:
      - 'release/**'
  
  pull_request:
    branches:
      - 'release/**'
    types: [closed]
  
  workflow_run:
    workflows: ["01 - Create Release"]
    types:
      - completed
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract-version-docker-image:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    outputs:
      BRANCH_NAME: ${{ steps.extract_branch.outputs.BRANCH_NAME }}
    steps:
      - name: Checkout repository if workflow_run
        if: github.event_name == 'workflow_run'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.workflow_run.head_branch }}

      - name: Checkout repository
        if: github.event_name != 'workflow_run'
        uses: actions/checkout@v4

      - name: Validate
        run: |
          echo "Validating if the branch is a release branch"
          echo "Branch: ${{ github.ref }}"
          
          if [[ ${{ github.ref }} == 'refs/heads/release/'* ]]; then
            echo "Valid branch"
          else
            echo "Invalid branch"
            exit 1
          fi

      - name: Extract branch name
        id: extract_branch
        uses: plataforma-ia/invillia-shared-pipelines/.github/actions/extract-branch-name@main
        with:
          prefix: 'refs/heads/release/'

  create-docker-image:
    needs: extract-version-docker-image
    uses: plataforma-ia/invillia-shared-pipelines/.github/workflows/create-docker-image.yml@main
    with:
      CONTAINER_NAME: 'aimanagment-bot'
      CONTAINER_TAG: '${{ needs.extract-version-docker-image.outputs.BRANCH_NAME }}'
      DOCKER_FILE: './Dockerfile'
      DOCKER_FILE_PATH: '.'
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: create-docker-image
    steps:
    - name: Workflow Dispatch and wait
      uses: the-actions-org/workflow-dispatch@v2.1.1
      with:
        workflow: '03 - Deploy Release'
        ref: ${{ github.href }}
        token: ${{ secrets.SHARED_REPO }}
        wait-for-completion: false
    


