name: '03 - Deploy Release'

on:
  workflow_run:
    workflows: ["02 - Create Docker Image"]
    types:
      - completed
    branches:
      - 'release/**'
  workflow_dispatch:

jobs:
  extract-version-docker-image:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    outputs:
      BRANCH_NAME: ${{ steps.extract_branch.outputs.BRANCH_NAME }}
    steps:
      - name: Checkout repository if workflow_run
        if: github.event_name == 'workflow_run'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.workflow_run.head_branch }}

      - name: Checkout repository
        if: github.event_name != 'workflow_run'
        uses: actions/checkout@v4

      - name: Validate
        run: |
          echo "Validating if the branch is a release branch"
          echo "Branch: ${{ github.ref }}"
          
          if [[ ${{ github.ref }} == 'refs/heads/release/'* ]]; then
            echo "Valid branch"
          else
            echo "Invalid branch"
            exit 1
          fi

      - name: Extract branch name
        id: extract_branch
        uses: plataforma-ia/invillia-shared-pipelines/.github/actions/extract-branch-name@main
        with:
          prefix: 'refs/heads/release/'

  deploy-prod:
    needs: extract-version-docker-image
    uses: plataforma-ia/invillia-shared-pipelines/.github/workflows/deploy-docker-image.yml@main
    with:
      CONTAINER_NAME: 'aimanagment-bot'
      CONTAINER_TAG: '${{ needs.extract-version-docker-image.outputs.BRANCH_NAME }}'
      AZURE_WEBAPP_NAME: 'invillia-aimanagment-aibot-api-002'
      ENVIRONMENT: 'production'
    secrets: inherit